### ISSUE TITLE
Error in Blade Language Server

### ISSUE THREAD

**Issue by CristianH033** [onecentlin/laravel-blade-snippets-vscode#46] opened 2018-02-16 14:03 UTC
Every time I'm going to write an HTML tag this error is displayed in the output console.

![error](https://user-images.githubusercontent.com/4079493/36311110-2fdf0222-12f8-11e8-91e4-69d91cf5fc49.PNG)

**Comment by V-ed** [comment] 2018-02-16 14:20
This issue is pretty much a duplicate of #44.

There is a temporary solution, which I explained [here](https://github.com/onecentlin/laravel-blade-snippets-vscode/issues/44#issuecomment-366247373).

**Comment by onecentlin** [comment] 2018-02-16 15:38
This issue also has been reported to vscode (https://github.com/Microsoft/vscode/issues/43823)

**Comment by V-ed** [comment] 2018-02-16 15:47
I can't understand how this is Microsoft's problem - even without emmet enabled for the `blade` syntax, this server problem occurs.

The issue Microsoft/vscode#43823 should not (in my opinion) be opened.

**Comment by tiansin** [comment] 2018-02-16 16:53
#47 remote error code.

**Closed** 2018-02-17 03:29 UTC
